### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by Hakiem** [vieapps/Components.WebSockets#1]
Hi members, am currently interested in implementing this package in my application. The application returns a json of available printers (online) as well as read a prn file, gets its bytes and send to a printer chosen from a web application. The web app is just a simple html with JavaScript under its hood. 

Now the problem is, i don't know how to start the server beyond the availed code
`var websocket = new WebSocket()
            {
                SupportedSubProtocols = new[] { "PrintersList", "Print" }
            };
            websocket.StartListen(46429);`

How do i handle the protocols?

I also saw some Event-driven delegates like 
`Action<ManagedWebSocket> OnConnectionEstablished;`

How do i build logic from them? I tried to set up something like 

`public class Program
    {
        static void Main(string[] args)
        {

            var websocket = new WebSocket()
            {
                SupportedSubProtocols = new[] { "PrintersList", "Print" }
            };
            websocket.StartListen(46429);

            Action<ManagedWebSocket> OnConnectionEstablished;
            Console.ReadLine();
        }

        static void OnConnectionEstablished()
        {
            //SendAsync()
        }
    }`

But still not getting any response whatsoever?

**Comment by quynh-ng** [comment]
Hi,

You can add some Event-driven delegates like into the snippet to handle your logic, and also listen for all incoming WebSocket connections on port number 46429 as a server.

```cs
var websocket = new WebSocket()
{
	SupportedSubProtocols = new[] { "PrintersList", "Print" },
	OnError = (webSocket, exception) =>
	{
		// your code to handle error here
	},
	OnConnectionEstablished = (webSocket) =>
	{
		// your code to handle connection when its established here, ex: webSocket.SendAsync(...)
	},
	OnConnectionBroken = (webSocket) =>
	{
		// your code to handle connection when its broken here
	},
	OnMessageReceived = (webSocket, receiveResult, data) =>
	{
		// your code to handle received messages here, ex: var msg = UTF8.GetString(data)
	}
};
websocket.StartListen(46429);
```
I just update the docs with examples of event-handlers => https://github.com/vieapps/Components.WebSockets#using-the-websocket-class
