### ISSUE TITLE
Cannot use WebSocket in .Net 4.7.2

### ISSUE THREAD

**Issue by Taliesin60** [vieapps/Components.WebSockets#12]
Hello.
I have a C# application in .Net 4.7.2 Framework. 
When I try to use vieapps.WebSocket, I have an error : 

"System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
Nom de fichier : 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

=== Informations d'état de liaison préalable ===
JRN : DisplayName = System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
JRN : Appbase = file:///C:/Git/UbikeyOffice/UbikeyOffice/UbikeyOfficeVertical/bin/x64/Debug/
JRN : PrivatePath initial = NULL
Assembly appelant : netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
===
JRN : cette liaison démarre dans le contexte de chargement de default.
JRN : utilisation du fichier de configuration de l'application : C:\Git\UbikeyOffice\UbikeyOffice\UbikeyOfficeVertical\bin\x64\Debug\UbikeyOfficeVertical.exe.Config
JRN : utilisation du fichier de configuration d'hôte : 
JRN : utilisation du fichier de configuration de l'ordinateur à partir de C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
JRN : une redirection a été trouvée dans le fichier de configuration de l'application : 4.0.0.0 redirigé vers 4.0.2.0.
JRN : référence post-stratégie : System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Git/UbikeyOffice/UbikeyOffice/UbikeyOfficeVertical/bin/x64/Debug/System.Runtime.InteropServices.RuntimeInformation.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Git/UbikeyOffice/UbikeyOffice/UbikeyOfficeVertical/bin/x64/Debug/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices.RuntimeInformation.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Git/UbikeyOffice/UbikeyOffice/UbikeyOfficeVertical/bin/x64/Debug/System.Runtime.InteropServices.RuntimeInformation.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Git/UbikeyOffice/UbikeyOffice/UbikeyOfficeVertical/bin/x64/Debug/System.Runtime.InteropServices.RuntimeInformation/System.Runtime.InteropServices.RuntimeInformation.EXE.
"

**Comment by quynh-ng** [comment]
Hi,

That about assembly binding of .NET Standard 2.0.

To resolve this issue, please install the package System.Runtime.InteropServices from NuGet  (https://www.nuget.org/packages/System.Runtime.InteropServices) into your project and lets Visual Studio makes the assembly bindings of your configuration  file.

**Comment by Taliesin60** [comment]
I delete all binding redirect and it's works 
Thank you
