### ISSUE TITLE
[Question] Thread safety

### ISSUE THREAD

**Issue by viktor-nikolaev** [vieapps/Components.WebSockets#3]
Sorry for that silly question - is it safe to call .SendAsync from multiple threads when acting as a client?

**Comment by quynh-ng** [comment]
Hi @Veikedo ,

That safe to call .SendAsync from multiple threads.

All messages are be queued when sending, so only one active thread dequeues and sends one-by-one at a time.

**Comment by viktor-nikolaev** [comment]
Thanks @quynh-ng !

**Comment by viktor-nikolaev** [comment]
Hi @quynh-ng , one more question about it.

If a message is not written immediately, then how can we know if write operation for that message failed?
eg I want to put some retry logic

**Comment by quynh-ng** [comment]
Hi,

All messages are written immediately, but being queued to make sure ONLY ONE active thread is process/send/write.

You can see the code here:

- Implementation of WebSocket: https://github.com/vieapps/Components.WebSockets/blob/f42a40c19bb009030ae8faea7f818df7d83dbe91/WebSocketImplementation.cs#L92
- Wrapper of ASP.NET (Core) WebSocket: https://github.com/vieapps/Components.WebSockets/blob/f42a40c19bb009030ae8faea7f818df7d83dbe91/WebSocketWrapper.cs#L74

**Comment by viktor-nikolaev** [comment]
Thanks for a quick reply,

As far as I can understand in `PutOnTheWireAsync` we can receive some inconsistency, please correct me if I'm wrong.

For example we have this code run by two threads:

        try
        {
          await managedWebSocket.SendAsync(message, WebSocketMessageType.Binary, true, cancellationToken);
        }
        catch (Exception e)
        {
          // some logic here
        }

Let's suppose first thread set `this._writing = true` and starts to dequeue from `this._buffers`. Meanwhile, second thread also pushes messages to `managedWebSocket.SendAsync` - so messages, pushed by the second thread, are processed by the first thread in `PutOnTheWireAsync` method.

In that case we won't catch exception in the second thread as it returned here:
https://github.com/vieapps/Components.WebSockets/blob/f42a40c19bb009030ae8faea7f818df7d83dbe91/WebSocketImplementation.cs#L102

but this exception would raise in the first thread.

**Comment by quynh-ng** [comment]
Hi,

The centralized point is a WebSocket connection, that is a single instance.

The active thread (first thread) will raise an exception when getting any error, and this exception will be captured and processed by the OnError event handler.

**Comment by quynh-ng** [comment]
Hi,

The centralized point is a WebSocket connection, and that instance can be processed from multiple threads. In my test/real world app, I haven't got any error of sending messages, event the connection is closed/dropped.

The WebSocket class has an event handler named "OnError" to process any error while processing, and the next release will have try/catch block to capture exceptions of .SendAsync methods in the WebSocket class.

**Comment by viktor-nikolaev** [comment]
Hi,
I also a bit worried about `this._writing` field - as there are no locks around it we can start writing to `this._stream` from two threads simultaneously. 

In my client code I put some locks around `socket.SendAsync`, so I can control it. But I can't control `PingPongManager` and afaik it also can put something on the wire.

**Comment by quynh-ng** [comment]
Hi,

The .SendPongAsync and .SendPingAsync methods are may put something on the wire when the .SendAsync is processing.

I haven't got any issue with ping/pong in my test (because the interval is 60 seconds), but I think that can cause some exception when working with very much threads. Do you think the method PutOnTheWire is need to be rework (with queue)?

**Comment by viktor-nikolaev** [comment]
Yeah, I think it should have some locking.

Currently I use socket only from one thread, but I have a requirement to send pings frequently. It works fine still, but I'm slightly concerned about it. 

I can probably handle this, will really appreciate if you can share your vision of how it can/should be reworked.

**Comment by quynh-ng** [comment]
Hi,

Here the .PutOnTheWireAsync method with SemaphoreSlim for working well with async/await. How do you think?

```csharp
private readonly SemaphoreSlim _lock = new SemaphoreSlim(1, 1);

async Task PutOnTheWireAsync(MemoryStream stream, CancellationToken cancellationToken)
{
	this._buffers.Enqueue(stream.ToArraySegment());
	await this._lock.WaitAsync(cancellationToken).ConfigureAwait(false);
	try
	{
		while (this._buffers.Count > 0)
			if (this._buffers.TryDequeue(out ArraySegment<byte> buffer))
				await this._stream.WriteAsync(buffer, cancellationToken).ConfigureAwait(false);
	}
	catch (Exception)
	{
		throw;
	}
	finally
	{
		this._lock.Release();
	}
}
```
