### ISSUE TITLE
OnConnectionEstablished - access to headers

### ISSUE THREAD

**Issue by petarkekez** [vieapps/Components.WebSockets#5]
Hi!

It would be nice to have access to the connection headers when OnConnectionEstablished is invoked.

Before connecting we can add additional headers with WebSocketOptions.AdditionalHeaders but this data can not be read when connection is established.

If it is fine by you I can add this to the WebSocket.cs and create a PullRequest?

My idea was to add the following line to line 487 of the file WebSocket.cs:
websocket.Extra["Header"] = header;

**Comment by quynh-ng** [comment]
Hi,

Did you mean the additional headers in the instance of WebSocketOptions?

**Comment by petarkekez** [comment]
Yes

**Comment by quynh-ng** [comment]
Hi,

If you wrap an existing WebSocket connection of ASP.NET/ASP.NET Core (https://github.com/vieapps/Components.WebSockets/blob/c34f96b4fb80cf978e1f4c9805b25c8b7440cb58/WebSocket.cs#L778), you already got 4 extra information (headers is included).

For the WebSocketImplementation class, I will update in the next release.

**Comment by petarkekez** [comment]
Hi, i am not using this in ASP.NET/ASP.NET Core.

Currently i am using it in an console app and eventually it will be a Windows service.

I am not sure how to use WrapAsync on a ManagedWebSocket or on WebSocket

**Comment by quynh-ng** [comment]
Hi,

The "Headers" property is now updated in ManagedWebSocket class. When act as a server, the headers contain all information that has been requested by client, when act as a client, the headers contain all information that sent to endpoint.

https://github.com/vieapps/Components.WebSockets/blob/ef5a36fd6d3aee690df38480998bc600f5c58bc1/WebSocket.cs#L1332

We will do the stress test in one week and plain to release this feature in the next version on nuget.

**Comment by petarkekez** [comment]
Sounds great. Thank you for the update

**Comment by petarkekez** [comment]
Hi, do you have the timeline when the next nuget release will be?

**Comment by quynh-ng** [comment]
Hi,
I need time to test to make sure the locking mechanism will not be the problem.
So the next nuget release will be available in the next few days (may be Apr 2 or 3).

**Comment by petarkekez** [comment]
Thank you for the information

**Comment by quynh-ng** [comment]
@petarkekez 
This component now got a new version on NuGet

**Comment by petarkekez** [comment]
Thanks for the update
