### ISSUE TITLE
websocket client + ping

### ISSUE THREAD

**Issue by peapodss** [vieapps/Components.WebSockets#7]
If I use the websocket client, can I use the ping function?
The source code seems to only have a ping function for the server side.

**Comment by quynh-ng** [comment]
Yes, of course.

Usually the WebSocket server will send ping frame to all client after a period of time.
But you can set the KeepAliveInterval (of the WebSocketOptions) to other value (default is TimeSpan.Zero) to send a ping frame when using the WebSocket as client role => https://github.com/vieapps/Components.WebSockets/blob/f66ee51f2951d1f1120eb216249511dddcfbecb5/WebSocket.cs#L783

And the options also includes some **Func** properties to define ping/pong data => https://github.com/vieapps/Components.WebSockets/blob/f66ee51f2951d1f1120eb216249511dddcfbecb5/WebSocketOptions.cs#L66

**Comment by peapodss** [comment]
Ok, i will try to use it like this, thanks a lot.
