### ISSUE TITLE
Custom close codes?

### ISSUE THREAD

**Issue by jerk** [vieapps/Components.WebSockets#8]
I can't seem to use custom close codes. It ends up becoming close code 1000.

**Comment by quynh-ng** [comment]
Please see the details of WebSocketCloseStatus at Microsoft Docs
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketclosestatus?view=netcore-3.1
The "custom close codes" must follow the WebSocketCloseStatus enum

**Comment by jerk** [comment]
Never mind, i think it was an error on my part, sorry about that.
